baseURL = "https://ismrm.github.io/mrpub/"
canonifyurls = true
languageCode = "en-us"
title = "MR-Pub"
theme = "hugo-now-ui"


googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
#enableGitInfo = true
publishDir = "public"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "RRSG 2021 Competition"
    url = "/competition/"
    pre = "<i class='now-ui-icons sport_trophy'></i>"
    weight = 1

[[menu.main]]
    name = "Submit"
    url = "https://docs.google.com/forms/d/e/1FAIpQLSf6R3ln9-xShUuvMMk_Rl8BZ79yjl4Sq2SzDw3TZcurDissLw/viewform"
    pre = "<i class='now-ui-icons arrows-1_cloud-upload-94'></i>"
    weight = 1


[[menu.footer]]
    identifier = "twitter"
    pre = "<i class='fa fa-twitter'></i>"
    url = "https://twitter.com/mrm_highlights"
    weight = 1
[[menu.footer]]
    identifier = "github"
    pre = "<i class='fa fa-github'></i>"
    url = "https://github.com/ismrm"
    weight = 2
[[menu.footer]]
    identifier = "copyright"
    name = "MIT"
    pre = "<i class='fa fa-balance-scale'></i>"
    url = "https://spdx.org/licenses/MIT"
    weight = 3


[params]
    tint = "nlgray"
    custom_css = ["css/highlight.min.css"]
    custom_js = []
    date_format = "Mon, Jan 2, 2006"
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
